-- Esquema mínimo para la app PHP + MySQL.
-- Ajustá los tipos y longitudes según tu proveedor.

CREATE DATABASE IF NOT EXISTS aapp_manager CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE aapp_manager;

-- Almacenamiento compacto del estado completo (backup rápido / sincronización)
CREATE TABLE IF NOT EXISTS app_state (
  id TINYINT UNSIGNED PRIMARY KEY,
  data JSON NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Entidades principales
CREATE TABLE IF NOT EXISTS saas (
  id VARCHAR(64) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  url VARCHAR(255) NOT NULL,
  logo_url VARCHAR(255) DEFAULT NULL,
  register_url VARCHAR(255) DEFAULT NULL,
  login_url VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS plans (
  id VARCHAR(64) PRIMARY KEY,
  saas_id VARCHAR(64) NOT NULL,
  frequency VARCHAR(50) NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  price DECIMAL(12,2) NOT NULL DEFAULT 0,
  features JSON DEFAULT NULL,
  variable_features JSON DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (saas_id) REFERENCES saas(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS extras (
  id VARCHAR(64) PRIMARY KEY,
  saas_id VARCHAR(64) NOT NULL,
  name VARCHAR(255) NOT NULL,
  price DECIMAL(12,2) NOT NULL DEFAULT 0,
  frequency VARCHAR(50) NOT NULL,
  features JSON DEFAULT NULL,
  variable_features JSON DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (saas_id) REFERENCES saas(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS campaigns (
  id VARCHAR(64) PRIMARY KEY,
  saas_id VARCHAR(64) NOT NULL,
  ad_name VARCHAR(255) NOT NULL,
  date DATE NOT NULL,
  daily_spend DECIMAL(12,2) NOT NULL DEFAULT 0,
  total_spend DECIMAL(12,2) NOT NULL DEFAULT 0,
  reach INT DEFAULT 0,
  views INT DEFAULT 0,
  cost_per_conversation DECIMAL(12,2) DEFAULT 0,
  notes TEXT,
  FOREIGN KEY (saas_id) REFERENCES saas(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS partners (
  id VARCHAR(64) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  company VARCHAR(255) DEFAULT NULL,
  email VARCHAR(255) DEFAULT NULL,
  phone VARCHAR(50) DEFAULT NULL,
  commission DECIMAL(5,2) DEFAULT 0,
  notes TEXT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS clients (
  id VARCHAR(64) PRIMARY KEY,
  saas_id VARCHAR(64) NOT NULL,
  plan_id VARCHAR(64) DEFAULT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) DEFAULT NULL,
  password VARCHAR(255) DEFAULT NULL,
  extra_ids JSON DEFAULT NULL,
  date DATE DEFAULT NULL,
  notes TEXT,
  links TEXT,
  FOREIGN KEY (saas_id) REFERENCES saas(id) ON DELETE CASCADE,
  FOREIGN KEY (plan_id) REFERENCES plans(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS domains (
  id VARCHAR(64) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  saas_id VARCHAR(64) NOT NULL,
  client_id VARCHAR(64) DEFAULT NULL,
  provider VARCHAR(255) DEFAULT NULL,
  status VARCHAR(50) DEFAULT 'Activo',
  notes TEXT,
  FOREIGN KEY (saas_id) REFERENCES saas(id) ON DELETE CASCADE,
  FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS resellers (
  id VARCHAR(64) PRIMARY KEY,
  saas_id VARCHAR(64) NOT NULL,
  source_type ENUM('plan','extra') NOT NULL,
  source_id VARCHAR(64) NOT NULL,
  cost_price DECIMAL(12,2) NOT NULL DEFAULT 0,
  sale_price DECIMAL(12,2) NOT NULL DEFAULT 0,
  delivery_time VARCHAR(255) DEFAULT NULL,
  requirements TEXT,
  FOREIGN KEY (saas_id) REFERENCES saas(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS pos_sales (
  id VARCHAR(64) PRIMARY KEY,
  buyer_name VARCHAR(255) NOT NULL,
  buyer_email VARCHAR(255) DEFAULT NULL,
  saas_id VARCHAR(64) NOT NULL,
  plan_id VARCHAR(64) DEFAULT NULL,
  extra_ids JSON DEFAULT NULL,
  date DATE NOT NULL,
  payment_method VARCHAR(50) NOT NULL,
  amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  notes TEXT,
  FOREIGN KEY (saas_id) REFERENCES saas(id) ON DELETE CASCADE,
  FOREIGN KEY (plan_id) REFERENCES plans(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS expenses (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  date DATE NOT NULL
) ENGINE=InnoDB;
